<?php
/**
 * Created by KaiQiang-use by PhpStorm.
 * User: fennu
 * Date: 2018/10/29
 * Time: 10:31
 */

namespace app\admin\controller;


use think\Controller;
use think\facade\Session;
use think\Request;

class Common extends User
{
    protected $id;
    protected $token;
    protected function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
        /** 检查登录 */
        if (Session::has("user")) {
            $this->id = Session::get("user")["id"];

            $this->token = md5("JuYouLi_" . md5($this->id . Session::get("user")["name"]));
            if ($this->token !==$this->request->param("token")) {
                return_msg(400, "token不正确！");
            }
            unset($this->request->param()["token"]);
            return true;
        } else {
            return_msg(400, "请登录");
        }
    }

    /**
     * 图片上传
     * @param null $path 设置的二级路径
     * @param $request
     */
    public function upload_img(Request $request)
    {
        $path = $request->post("path");
        $file = request()->file('img');
        //移动图片
        $dir = "uploads/" . $path;
        $info = $file->validate(['size' => 5 * 1024 * 1024, 'ext' => 'jpg,png,gif,jpeg'])->move($dir);

        if ($info) {
            //文件上传成功
            //获取文件路径
            $goods_logo = $info->getSaveName();
            $goods_logo = str_replace('\\', '/', $goods_logo);
            return_msg(200, 'success',  $dir . $goods_logo);
        } else {
            $error = $file->getError();
            return_msg(400, $error);
        }
    }
}