<?php

namespace app\agent\controller;

use think\Controller;
use think\facade\Session;
use think\Request;

class Common extends Controller
{
    protected $agent_id;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        /** 检查登录 */
        if (Session::has("user")) {
            $this->agent_id = Session::get("user")["id"];
            return true;
        } else {
            return_msg(400, "请登录");
        }
    }

}
